<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'nha-dat-ban' => 'nha-dat-ban',
    'nha-dat-cho-thue' => 'nha-dat-cho-thue',
    'du-an' => 'du-an',
    'dang-tin' => 'dang-tin',
    'tin-tuc' => 'tin-tuc',
    'goi-gia' => 'goi-gia',
    'tro-chuyen' => 'tro-chuyen',
    'thong-bao' => 'thong-bao',
    'cai-dat' => 'cai-dat',
    'cap-nhat' => 'cap-nhat',
    'danh-sach-tin-dang' => 'danh-sach-tin-dang',
    'so-sanh' => 'so-sanh',
];
