<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'homepage' => 'MetVuong.com Vietnamese Real Estate, Houses and Apartments',
    'nha-dat-ban' => 'Vietnamese Real Estate for Sale',
    'nha-dat-cho-thue' => 'Vietnamese real estate for rent, apartments for rent',
    'du-an' => 'Developments',
    'dang-tin' => 'Post a property, post a listing',
    'tin-tuc' => 'Vietnamese News',
    'services' => 'Services',
];
